version: '3'
services:
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
  anagram:
    image: jeremyudis/anagram
    ports:
      - "3000:8080"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/system_health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
     - redis